name: 'postgres'

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_db:/var/lib/postgresql/data
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - network1
    
networks:
  network1:
    name: docker_network
    external: true

volumes:
  postgres_db:
    name: postgres_db
    driver: local